### ISSUE TITLE
Doesnt work on VPS

### ISSUE THREAD

**Issue by BhawaniGarg** [vikas5914/Facebook-Video-Downloader#1]
Hi i have upload all the files but it looks like it doesnt work on VPS 

Server details : Apache/2.2.15 (CentOS)

Demo: http://thebhawanigarg.com/read/tools/facebook/

My vps is using php version 5.3.x( if this is the issue then can you make it work in this version)

**Comment by vikas5914** [comment]
Can you post your error log from apache and php .

**Comment by BhawaniGarg** [comment]
Warning: date(): It is not safe to rely on the system's timezone settings. You are *required* to use the date.timezone setting or the date_default_timezone_set() function. In case you used any of those methods and you are still getting this warning, you most likely misspelled the timezone identifier. We selected 'Europe/Moscow' for 'MSD/4.0/DST' instead in /home/username/read/tools/facebook/index.php on line 87

**Comment by BhawaniGarg** [comment]
when i visit : http://thebhawanigarg.com/read/tools/facebook/main.php it says thebhawanigarg.com is currently unable to handle this request.
HTTP ERROR 500 But the demo url gives diff error

**Comment by BhawaniGarg** [comment]
got one more error : Warning: file_get_contents(): Filename cannot be empty in /home/username/read/tools/facebook/main.php on line 17

**Comment by BhawaniGarg** [comment]
resolved everything ... your script doesnt work on php 5.3 i have upgraded my php version
