### ISSUE TITLE
Mobile video link Download 

### ISSUE THREAD

**Issue by InsertCart** [vikas5914/Facebook-Video-Downloader#11]
How we can download video on mobile devices 

like convert link 
https://m.facebook.com/story.php?story_fbid=483875838661351&id=284024335313170

to pc download able ?

**Comment by vikas5914** [comment]
@InsertCart that's not a video link. it's story link.  let me see if I can fetch video link from that page source code.

**Comment by InsertCart** [comment]
Yes, Because most of user are from mobile device and facebook allow user to copy story link for every video. Just wants to know if there is any way to fetch direct video from mobile version as well.

**Comment by InsertCart** [comment]
I have tried some website which works fine in garbing video link from mobile story as well

Like
http://www.downvids.net/ 

Did you manage to fix this issue ?

**Comment by vikas5914** [comment]
Try the v4 and let me know.
