### ISSUE TITLE
2 generated links only

### ISSUE THREAD

**Issue by jhaylee2016** [vikas5914/Facebook-Video-Downloader#12]
hi sir I found out that your script only generated 2 download links which is sdlink and hdlink,,but when you open a facebook video they have 4 resolution which 720p,480p,360p and 240p...how to implement on your script to generate those resolutions..thank you...

**Comment by vikas5914** [comment]
@jhaylee2016 best way to find is to use IDM and capture the 720p link then find that link inside facebook page code. then scrap it using PHP.

**Comment by dungvaph03374** [comment]
change preg_match to FBQualityLabel=\"720p\... but it's just a dash video meaning no sound, so you have to add another function to get audio link like audio_channel_configuration:2011\" value=\"2\"/>\x3CBaseURL>

**Comment by vikas5914** [comment]
FIxed in v4
