### ISSUE TITLE
Show file size

### ISSUE THREAD

**Issue by dev-myatminsoe** [vikas5914/Facebook-Video-Downloader#17]
Everything works fine. But how can I show file sizes for sd and hd vidoes

**Comment by vikas5914** [comment]
You can't unless you download the whole video on the server first.

**Comment by dev-myatminsoe** [comment]
I thought the data from facebook contains the file size since the Facebook Lite app shows the size. But it doesn't. But you can get the file size by using `curl_getinfo` on video URL. I could create a pull request if you want to.

**Comment by vikas5914** [comment]
I create this for to show people how can you fetch the download link.  It was never meant to create an actual Downloader. 

So right now this does not come in the roadmap. 

If you want to help, you can make a pull request for different video quality instead of just SD and HD
