### ISSUE TITLE
Private Facebook  Hd Videos & Facebook Video Downloader ( Index page )

### ISSUE THREAD

**Issue by bouchaibcharioui** [vikas5914/Facebook-Video-Downloader#19]
Hello Sir , I have a problem with Downloading Private Facebook Hd videos , when I click "MP4 HD" button to download the video with HD Quality it Downloads an empty video named "hd.mp4" .
Also About Facebook Video Downloader ( Index page ) in the text box Where they say to me to paste the facebook video URL , I paste it but I don't find the button to click to download the video , I see just a text in the Right of text box named "Download!"

Please can you Fix this problems , and thank you so much :+1:  :)))

**Comment by vikas5914** [comment]
Fixed in V4
