### ISSUE TITLE
Facebook video voice issue.

### ISSUE THREAD

**Issue by veed76** [vikas5914/Facebook-Video-Downloader#23]
Hi @vikas5914 
Thank you for this code.
I used the code and added facebook video link and when I open it new tab the video voice is not getting.
Example:
```
https://scontent.fstv5-1.fna.fbcdn.net/v/t39.25447-6/10000000_140729723781589_6315447710579546365_n.mp4?_nc_cat=103&efg=eyJ2ZW5jb2RlX3RhZyI6ImRhc2hfb2VwX2hxNV9mcmFnXzJfdmlkZW8ifQ%3D%3D&_nc_oc=AQljCHOHWAjIVwEofGXRdqQLhCAz-D_z6ucJKSP45BPV24Fng7ttXxh4ZvaEFTrlKMY&_nc_ht=scontent.fstv5-1.fna&oh=8584b9ecea000b9c07d917178f3a1b55&oe=5DAEBF58
```

**Comment by vikas5914** [comment]
Hi, 

Can you provide the facebook video link?

**Comment by veed76** [comment]
Hi, @vikas5914 
here is the URL: ` https://www.facebook.com/Filmymantravideos/videos/594952571029862 `

you can try with any URL.

**Comment by techinnov-974** [comment]
Hello, indeed once the download is complete when you start the video no sound is broadcast

**Comment by vikas5914** [comment]
Hi Everyone, 

I have figured it out the issue. This links indeed does not have audio in them. 

What facebook doing is It plays the different resolution of Video with separate audio.

There are two solutions to this: 

1) Download the video and audio separately and combine them.
2) There are SD and HD URL which has Audion in them.

I will try to implement the second solution on weekends.

**Comment by vikas5914** [comment]
@veed76  @techinnov-974 

Please try now:  https://fbvideo-download.herokuapp.com/

and let me know.
