### ISSUE TITLE
not working 

### ISSUE THREAD

**Issue by adamwoo2444** [vikas5914/Facebook-Video-Downloader#26]
Its not working after uploading on server.

**Comment by vikas5914** [comment]
@adamwoo2444 Can you please provide more info on this.

**Comment by adamwoo2444** [comment]
This is the url you can check, its not working on server . http://3url.ml/Facebook-Video-Downloader/

**Comment by vikas5914** [comment]
@adamwoo2444 Your server is throwing 500 internal server error. 

Please check the server logs for more information.
