### ISSUE TITLE
Not Working in non google app engine environment  

### ISSUE THREAD

**Issue by MusaSiddiqui** [vikas5914/Facebook-Video-Downloader#3]
Hi Dear, When I Uploaded The Script, It Was Not Working, It Shows This, http://prnt.sc/camu6l
I Don't Know How To Use It Or Install It etc. Please Help

**Comment by vikas5914** [comment]
this script is designed to work with google app engine platform . you need to move all folder inside "static" to root folder .

**Comment by MusaSiddiqui** [comment]
Thank you dear, it is working now :)
What is Graph API Video Downloader and why it is not working ?
And can you add youtube downloading option in this script if I give you files of another working script ? That script downloads the videos from youtube, but i want that feature in this script

**Comment by MusaSiddiqui** [comment]
and a website http://fbdown.net/ is using your script, but whenever we paste video link in the box and click on download, a page opens where user can get the download link, it is good for increasing the pageviews, specially when we are using Google Adsense
in your script, it load and show download link on the same page, 
how can i get the feature of the website mentioned above ?

**Comment by vikas5914** [comment]
1. Graph api was failed attempt to fetch video streaming/downloading link using Facebook API . 
2. fbdown.net is not using my script . if you want like that  you need to make changes in index.php and main.php

basically you create a form in index.php which has one input box and it will post to main.php where it get download link and show it ..

**Comment by MusaSiddiqui** [comment]
Thanks dear :)
Just checked another issue, your script is not displaying images, check http://prnt.sc/cb6qii

**Comment by vikas5914** [comment]
check this : http://prntscr.com/cb70jp

**Comment by MusaSiddiqui** [comment]
test again on mozilla firefox, 
just checked, showing thumbnail on chrome, not on firefox 
I am using firefox 47.0 
facebook private video downloader not working, checked 2 times, 1st tried to download a video posted in a group, then one of my friend uploaded video with privacy (friends only), i tried to download it, but i was unable to download it

**Comment by vikas5914** [comment]
for picture i use facebook graph api . for public video it should get picture but for some reason it asking for token to get picture . 

Private video has problem . sometime it work some time it doesn't . i think facebook changed something . i will look into it .

**Comment by vikas5914** [comment]
can you post facebook video link which is public and images is not showing .
