### ISSUE TITLE
Public Group Videos

### ISSUE THREAD

**Issue by NovaStudioApps** [vikas5914/Facebook-Video-Downloader#31]
HI,
I Can't download public group's videos!

**Facebook Video url**
Link: https://web.facebook.com/100022590922714/videos/963077977636517/

**Comment by vikas5914** [comment]
@NovaStudioApps Thanks for the report. 

I will look into this.

**Comment by Gimenz** [comment]
i've tried change user agent into Nokia 2700 Classic user-agent, and change url to mbasic.facebook.com, it's worked. 

maybe you can implement it 😄

**Comment by vikas5914** [comment]
@Gimenz can you provide a code example of the changes?

**Comment by Gimenz** [comment]
ah i forgot to says, on  my code it needed cookie

**Comment by peter279k** [comment]
After visiting the link, it seems that the video is unavailable now:

![image](https://user-images.githubusercontent.com/9021747/155530794-2ea1eddf-62c1-4a30-9faf-e413d628e253.png)
