### ISSUE TITLE
how to run it locally???

### ISSUE THREAD

**Issue by sandeshkoiralaa** [vikas5914/Facebook-Video-Downloader#38]
how to run it locally before hosting it on a website? 
Thank you in advance

**Comment by vikas5914** [comment]
@sandeshkoiralaa 

This is a normal PHP website. Nothing fancy. Ignore the docker file. It's only for myself. 

1. Clone the repo. 
2. do `composer install `

then you can just use XMPP or anything else to run as a normal PHP website.

**Comment by sandeshkoiralaa** [comment]
okay let me check

**Comment by vikas5914** [comment]
Check and let me know. If you still get error, reopen this issue.

**Comment by sandeshkoiralaa** [comment]
i'm getting problem in PHP version  how can I solve this?

![issue](https://user-images.githubusercontent.com/97677402/187976460-261fa9e1-5e33-45a0-ae4e-7b312b2fb717.png)

**Comment by AIhasArrived** [comment]
for someone who forgot how or what pho is all about, If I remember well xmpp or similar things would allow you to "host" some link, then a tab will open, = a UI, where you insert a link of a video, then press download?
Could you elaborate on the steps after "composer install"?

**Comment by vikas5914** [comment]
@AIhasArrived I have added a new version.. just copy paste the code and it should work without any issue. No need for Composer or anything.

**Comment by AIhasArrived** [comment]
Thanks!!
