### ISSUE TITLE
i'm getting problem in PHP version how can I solve this?

### ISSUE THREAD

**Issue by sandeshkoiralaa** [vikas5914/Facebook-Video-Downloader#39]
![issue](https://user-images.githubusercontent.com/97677402/187980094-ab24010a-2fdd-4288-a066-472697e956a5.png)

**Comment by vikas5914** [comment]
All the information to solve the error is already given in the image. I suggest you read it again. 

You are using an old version of Monolog. Since you have PHP version v8.1, I suggest you use v3 of Monolog.

For more information check: https://github.com/Seldaek/monolog
