### ISSUE TITLE
No Download links here by 

### ISSUE THREAD

**Issue by ashirali44** [vikas5914/Facebook-Video-Downloader#41]
![image](https://user-images.githubusercontent.com/38634960/209150851-6e356295-b6fb-47fe-800f-a7c8e5854bed.png)

I have uploaded it on the server it gives me the error Login into Facebook or now downloading links.
Anyways locally script is working fine.

**Comment by ashirali44** [comment]
just happens on /post/ urls other url like watch works fine

**Comment by vikas5914** [comment]
Can you provide the link?

**Comment by ashirali44** [comment]
https://www.facebook.com/groups/5314266812017844?multi_permalinks=5569225806521942&hoisted_section_header_type=recently_seen
@vikas5914  its working on demo url plus on my local host but not work on my website

**Comment by ashirali44** [comment]
<img width="1013" alt="Screenshot 2022-12-23 at 1 01 19 PM" src="https://user-images.githubusercontent.com/38634960/209298195-6581ec4e-912b-4d3d-9c50-3b6291fa0e30.png">
This is what I sometimes get or sometimes not downloading links.

**Comment by vikas5914** [comment]
@ashirali4 Can you provide your website link?
