### ISSUE TITLE
Downloadable path not fetching

### ISSUE THREAD

**Issue by fahdi53** [vikas5914/Facebook-Video-Downloader#43]
when we try to fetching url its not working.

**Comment by farhad-ulllah** [comment]
same problem download path is not fetching

**Comment by farhad-ulllah** [comment]
> when we try to fetching url its not working.

can you fix this or not

**Comment by vikas5914** [comment]
Can you guys at least provide a URL instead of spamming?

**Comment by fahdi53** [comment]
yeah you can check any url for the like: https://www.facebook.com/reel/3581580972164848

**Comment by vikas5914** [comment]
@fahdi53 I did

![image](https://github.com/vikas5914/Facebook-Video-Downloader/assets/7912297/aadd83eb-b032-4de4-86f4-4e32fa6e7ffd)

**Comment by fahdi53** [comment]
yeah its working as you mentioned site: https://facebook-video-downloader.fly.dev
but not working when i am checking this code, please review your uploaded code once

**Comment by vikas5914** [comment]
@fahdi53 it's not working on your localhost?

**Comment by fahdi53** [comment]
yeah its not working all time it just loading as i mentioned ss
https://drive.google.com/file/d/1GxAjPtp0P7vpZ1NiUtM8HSK5UulZFK-M/view?usp=sharing

**Comment by vikas5914** [comment]
@fahdi53 open the network tab in the console. And see the request to 'main.php`; when you click on that, it will show errors.

**Comment by farhad-ulllah** [comment]
i make api in laravel from this php code now in the response it only gave me title its stop working from tomorrow there is no error  the problem is they are not gave me the dawonload link

**Comment by vikas5914** [comment]
@farhad-ulllah, can you show the code?? also give me link that you are trying.

**Comment by LuMitchell** [comment]
https://www.facebook.com/100022317116355/videos/995379191779691

not work, need login

**Comment by vikas5914** [comment]
@LuMitchell This video is only available for registered users. We only support public videos.
