### ISSUE TITLE
Downloafd Videos not working it throws error

### ISSUE THREAD

**Issue by usmandeadstock** [vikas5914/Facebook-Video-Downloader#45]
**Describe the bug**
The Downloading videos not working as update for facebook. it is getting error 
"HTTP/2 302  returned for \"https://www.fb.watch/login/?next=https%3A%2F%2Fwww.fb.watch%2Flogin%2F%3Fnext%3Dhttps%253A%252F%252Fwww.fb.watch%252Flogin%252F%253Fnext%253Dhttps%25253A%25252F%25252Fwww.fb.watch%25252Flogin%25252F%25253Fnext%25253Dhttps%2525253A%2525252F%2525252Fwww.fb.watch%2525252Flogin%2525252F%2525253Fnext%2525253Dhttps%252525253A%252525252F%252525252Fwww.fb.watch%252525252Flogin%252525252F%252525253Fnext%252525253Dhttps%25252525253A%25252525252F%25252525252Fwww.fb.watch%25252525252Flogin%25252525252F%25252525253Fnext%25252525253Dhttps%2525252525253A%2525252525252F%2525252525252Fwww.fb.watch%2525252525252Flogin%2525252525252F%2525252525253Fnext%2525252525253Dhttps%252525252525253A%252525252525252F%252525252525252Fwww.fb.watch%252525252525252Flogin%252525252525252F%252525252525253Fnext%252525252525253Dhttps%25252525252525253A%25252525252525252F%25252525252525252Fwww.fb.watch%25252525252525252Flogin%25252525252525252F%25252525252525253Fnext%25252525252525253Dhttps%2525252525252525253A%2525252525252525252F%2525252525252525252Fwww.fb.watch%2525252525252525252Flogin%2525252525252525252F%2525252525252525253Fnext%2525252525252525253Dhttps%252525252525252525253A%252525252525252525252F%252525252525252525252Fwww.fb.watch%252525252525252525252Flogin%252525252525252525252F%252525252525252525253Fnext%252525252525252525253Dhttps%25252525252525252525253A%25252525252525252525252F%25252525252525252525252Fwww.fb.watch%25252525252525252525252Flogin%25252525252525252525252F%25252525252525252525253Fnext%25252525252525252525253Dhttps%2525252525252525252525253A%2525252525252525252525252F%2525252525252525252525252Fwww.fb.watch%2525252525252525252525252Flogin%2525252525252525252525252F%2525252525252525252525253Fnext%2525252525252525252525253Dhttps%252525252525252525252525253A%252525252525252525252525252F%252525252525252525252525252Fwww.fb.watch%252525252525252525252525252Flogin%252525252525252525252525252F%252525252525252525252525253Fnext%252525252525252525252525253Dhttps%25252525252525252525252525253A%25252525252525252525252525252F%25252525252525252525252525252Fwww.fb.watch%25252525252525252525252525252Flogin%25252525252525252525252525252F%25252525252525252525252525253Fnext%25252525252525252525252525253Dhttps%2525252525252525252525252525253A%2525252525252525252525252525252F%2525252525252525252525252525252Fwww.fb.watch%2525252525252525252525252525252Flogin%2525252525252525252525252525252F%2525252525252525252525252525253Fnext%2525252525252525252525252525253Dhttps%252525252525252525252525252525253A%252525252525252525252525252525252F%252525252525252525252525252525252Fwww.fb.watch%252525252525252525252525252525252Flogin%252525252525252525252525252525252F%252525252525252525252525252525253Fnext%252525252525252525252525252525253Dhttps%25252525252525252525252525252525253A%25252525252525252525252525252525252F%25252525252525252525252525252525252Fwww.fb.watch%25252525252525252525252525252525252Flogin%25252525252525252525252525252525252F%25252525252525252525252525252525253Fnext%25252525252525252525252525252525253Dhttps%2525252525252525252525252525252525253A%2525252525252525252525252525252525252F%2525252525252525252525252525252525252Fwww.fb.watch%2525252525252525252525252525252525252Flogin%2525252525252525252525252525252525252F%2525252525252525252525252525252525253Fnext%2525252525252525252525252525252525253Dhttps%252525252525252525252525252525252525253A%252525252525252525252525252525252525252F%252525252525252525252525252525252525252Ffb.watch%252525252525252525252525252525252525252FnvuKtUEAAa%252525252525252525252525252525252525252F\"."
success
: 
false
**To Reproduce**

**Expected behavior**

**Screenshots**

**Facebook Video url**
Link:

**Additional context**

**Comment by vikas5914** [comment]
@usmandeadstock Hey, The code is working fine; however, the issue is that Facebook is blocking the IP address. You need to use a residential proxy to bypass the block.
