### ISSUE TITLE
sd and Hd url not found

### ISSUE THREAD

**Issue by M-Shahroz** [vikas5914/Facebook-Video-Downloader#46]
SD and HD url not found  in view source of live server it give me login details how can i fix this

**Comment by vikas5914** [comment]
@M-Shahroz Please provide details like which Url you are trying to download

**Comment by M-Shahroz** [comment]
https://m.facebook.com/story.php?story_fbid=pfbid02xFZ43Xo3rLLcTL8ntL5uwZ7WnyJmATqonyVze3UFsHJQiFGGhyGrLpemPpdgt8Tpl&id=100090169778579

**Comment by M-Shahroz** [comment]
Sir I use your code working fine in local server but in live server view
source which I get against video url not have pattern keys means
browser_native_sd_url and browser_native_hd_url. In live server it give
login details in view source plz help me

**Comment by vikas5914** [comment]
@M-Shahroz You will better proxies to bypass the login ..
