### ISSUE TITLE
facing login and signup issue at live server

### ISSUE THREAD

**Issue by M-Shahroz** [vikas5914/Facebook-Video-Downloader#48]
**Describe the bug**
i make facebook video downloader api using your code but your code working fine on local server, but on live server it give me response sometime and most of the cases at live server it give me login and sign up error. how can i fix this plz sir help me

**Comment by vikas5914** [comment]
@M-Shahroz Create a free account on this proxy https://www.webshare.io/?referral_code=vzlqp314yhj3

and then  try.

**Comment by M-Shahroz** [comment]
Ok, I will try.
