### ISSUE TITLE
Download Button Issue

### ISSUE THREAD

**Issue by sunnyujjawal** [vikas5914/Facebook-Video-Downloader#9]
Thanks for the awesome code.
https://github.com/vikas5914/Facebook-Video-Downloader

I installed it on server but download button is not working.
Please help

**Comment by Arman143** [comment]
its working fine with us https://ytfb.download/fb/

**Comment by sunnyujjawal** [comment]
@Arman143 u r using same code or any change required?
url_fopen is also ON in cpanel

**Comment by hamza0200** [comment]
Hi,

I have installed your code on my server but it didn't worked. I have uploaded at:

http://w3programmings.com/fb-downloader/

When I enter facebook video URL to download, it gives error "Error retrieving the download link for the url. Please try again later".

However, the same code worked fine when I installed it in my localhost (own laptop). Please let me know if there configurations needed on server.  The "allow_url_fopen" is enabled on my server.

Thanks

**Comment by vikas5914** [comment]
@hamza0200  and @sunnyujjawal  can you paste error log from your server?

**Comment by hamza0200** [comment]
I am unable to view error logs. Can you suggest me possible solutions for this?

The script working fine at my local laptop.

**Comment by sunnyujjawal** [comment]
@vikas5914 issue solved by @Arman143 
Thanks
